on:
    pull_request: 
          types:
           - opened
  
jobs:
    pr-action:
        runs-on: ubuntu-latest
        permissions:
          issues: write
          pull-requests: write
        steps:     
          - name: Post PR Comment
            uses: fsainovich/docker-action-pr-giphy-comment@main
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
          - name: Post JavaScript PR Comment
            uses: fsainovich/js-action-pr-giphy-comment@v1.0.1-alpha
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

