name: Deployment - Reusable Workflow

on:
    workflow_call: 
        inputs:
          mongodb-uri:
            required: true
            type: string            
          kubectl-version:
            description: "Provide the required kubectl verion"
            default: v1.26.0
            required: false
            type: string            
          k8s-manifest-dir:
            description: "Directory containing kubernetes manifests files"
            default: kubernetes/
            required: true
            type: string   
          environment:
            description: "Provide the Deployment Environment"
            default: dev
            required: true
            type: string      
        secrets:
          k8s-kubeconfig:            
            required: true
          mongodb-password:
            required: true

jobs:
    reuse-deploy:
      name: Deploy to ${{ inputs.environment }}
      runs-on: ubuntu-latest
      environment: 
        name: ${{ inputs.environment }}
        url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      outputs:
        INGRESS_HOST_OUTPUT: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Install Kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: ${{ inputs.kubectl-version }}

        - name: Set Kubeconfig File
          uses: azure/k8s-set-context@v3
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.k8s-kubeconfig }}
                    
        - name: Fetch Kubernetes Cluster Details
          run: |
            echo kubectl version --short
            echo -------------------------------------------------------------
            echo kubectl get nodes

        - name: Get Ingress Address
          run: |
            #echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
            echo "INGRESS_IP=127.0.0.1" >> $GITHUB_ENV      

        - name: Update Kubernetes Deployment
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS:  ${{ vars.REPLICAS }}
            IMAGE: ${{ vars.DOCKER_HUB_USERANME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ inputs.mongodb-uri }}
            
        - name: Check Files
          run: |
            cat ${{ inputs.k8s-manifest-dir }}*.yaml
            
        - name: Create MongoDB Secret
          run: |
            kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI='${{ env.MONGO_URI }}' \
            --from-literal=MONGO_USERNAME='${{ vars.MONGO_USERNAME }}' \
            --from-literal=MONGO_PASSWORD='${{ secrets.mongodb-password }}' \
            --save-config \
            --dry-run=client \
            -o yaml
            #-o yaml | kubectl apply -f -

        - name: Deploy to ${{inputs.environment}} ENV
          run: |
            echo kubectl apply -f ${{ inputs.k8s-manifest-dir }}
            
        - name: Set App Ingress Host URL
          id: set-ingress-host-address
          run: |                        
            echo "APP_INGRESS_HOST=solar-dev.fsainovich.xyz" >> "$GITHUB_OUTPUT"
            #echo "APP_INGRESS_HOST=$(k get -n ${{ vars.NAMESPACE }} ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}" | grep -v %)" >> "$GITHUB_OUTPUT"

